{% set version = "2.1.0" %}
{% set jpeg_version = os.environ.get('JPEG_VERSION', '9')|string %}
{% set libpng_version = os.environ.get('LIBPNG_VERSION', '>=1.6.21,<1.7')|string %}
{% set libpng_string = libpng_version.split(',')[0].split('=')[-1].replace('"', '') %}
{% set build_number = "5" %}

package:
  name: bob.io.image
  version: {{ version }}

source:
  fn: bob.io.image-{{ version }}.zip
  md5: d917a7b780a62c201032720f6ca7e6fd
  url: https://pypi.io/packages/source/b/bob.io.image/bob.io.image-{{ version }}.zip

build:
  number: {{ build_number }}
  string: py{{ environ.get('CONDA_PY', '') }}_jpeg{{ jpeg_version }}_libpng{{ libpng_string }}_{{ build_number }}
  skip: true  # [win]

requirements:
  build:
  - python
  - setuptools
  - bob.extension
  - bob.blitz
  - bob.core
  - bob.io.base
  - giflib
  - libpng {{ libpng_version }}
  - jpeg {{ jpeg_version }}*
  - libtiff 4.0.*
  - boost 1.60.*
  - pkg-config

  run:
  - python
  - bob.extension
  - bob.blitz
  - bob.core
  - bob.io.base
  - giflib
  - libpng {{ libpng_version }}
  - jpeg {{ jpeg_version }}*
  - libtiff 4.0.*
  - boost 1.60.*

test:
  commands:
  - nosetests -sv bob.io.image

  imports:
  - bob
  - bob.io
  - bob.io.image

  requires:
  - nose

about:
  home: http://github.com/bioidiap/bob.io.image
  license: Modified BSD License (3-clause)
  summary: Image I/O support for Bob

extra:
  recipe-maintainers:
  - 183amir
