{% set version = "2.1.1" %}
{% set build_number = "0" %}

{% set jpeg_version = os.environ.get('JPEG_VERSION', '9')|string %}
{% set libpng_version = os.environ.get('LIBPNG_VERSION', '>=1.6.21,<1.7')|string %}
{% set libpng_string = libpng_version.split(",")[0].split("=")[-1].replace("\"", "") %}
{% set build_string = "py{}_jpeg{}_libpng{}_{}".format(environ.get('CONDA_PY', ''), jpeg_version, libpng_string, build_number) %}

package:
  name: bob.io.image
  version: {{ version }}

source:
  fn: bob.io.image-{{ version }}.zip
  md5: 0b43b08ddcf83c0464203b60bcc36ac5
  url: https://pypi.io/packages/source/b/bob.io.image/bob.io.image-{{ version }}.zip

build:
  number: {{ build_number }}
  string: {{ build_string }}
  skip: true  # [win]

requirements:
  build:
  - python
  - setuptools
  - bob.extension
  - bob.blitz
  - bob.core
  - bob.io.base >=2.0.9
  - giflib
  - libpng {{ libpng_version }}
  - jpeg {{ jpeg_version }}*
  - libtiff 4.0.*
  - boost 1.61.*
  - cmake
  - pkg-config

  run:
  - python
  - bob.extension
  - bob.blitz
  - bob.core
  - bob.io.base >=2.0.9
  - giflib
  - libpng {{ libpng_version }}
  - jpeg {{ jpeg_version }}*
  - libtiff 4.0.*
  - boost 1.61.*

test:
  commands:
  - nosetests -sv bob.io.image

  imports:
  - bob
  - bob.io
  - bob.io.image

  requires:
  - nose

about:
  home: http://github.com/bioidiap/bob.io.image
  license: Modified BSD License (3-clause)
  summary: Image I/O support for Bob

extra:
  recipe-maintainers:
  - 183amir
