# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "cYrKlL/xYCFzzvIQbCV1sXpVZcOU00IqfznUfQpGMK4kJFJVM1xuI5QgqHYZ54fc3KpMCo6TzoH58GkoUp+FX0BF0ppwhnZvguywEKiSf8AFUPO7/5O08w1mK6eQgSiriQc/kRA5VbXqqbjke1Ej4eLkfI5CH+vxsqIYCiRo2CPX/SIQcseFlxG/eGRcUU2YsPyBxgHduqg7XjSPJ/JjSQS46vEV1Nod1hqsgnNBf+Nskrx/I+VHoBmyrw+tJbMQ7ukDXJ4ysTKTyeTQtMHlo76tlo75k7JkMZdZpMdRD2n4m4GcuDetzRc4ZPX8XJ/DtAT56banbB6MnMXVzXNwT8gqumd56QDrHtuetxlg7e/IgsJNZDeKw6+w+QOkOEX7Cg7Go6xIkfFT2ZRQ79M55r+m0W58WhwjpPjD8xuLUz4bSfe9DpxcNPO8HoOB9iSUbtADHT+33inOW+9FGek6TmsAQ5YHuNxQd3PwbveJYEAaXPih4kHi5JeIfVd2SMReAd8WePvGdvrrXHCmAN9mDTtnlYDIcPpT7s8eUvxStG9VaSBW0zs96qWwidLriNtC3zEZAWAIcrGKEF4E/tdPnjM8LdttsjQxG8awdAnzFbsc0W1ShRUIJLwKdrQzVQuQ4edkOPzttTWpUtenNRWwY25SojiLvSsUj0YhxJ6cdpg="


before_install:
    - brew remove --force $(brew list)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH

      conda update --yes conda
      conda install --yes conda-build jinja2 anaconda-client
      conda config --add channels conda-forge
      

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
