travis:
  secure:
    BINSTAR_TOKEN: cYrKlL/xYCFzzvIQbCV1sXpVZcOU00IqfznUfQpGMK4kJFJVM1xuI5QgqHYZ54fc3KpMCo6TzoH58GkoUp+FX0BF0ppwhnZvguywEKiSf8AFUPO7/5O08w1mK6eQgSiriQc/kRA5VbXqqbjke1Ej4eLkfI5CH+vxsqIYCiRo2CPX/SIQcseFlxG/eGRcUU2YsPyBxgHduqg7XjSPJ/JjSQS46vEV1Nod1hqsgnNBf+Nskrx/I+VHoBmyrw+tJbMQ7ukDXJ4ysTKTyeTQtMHlo76tlo75k7JkMZdZpMdRD2n4m4GcuDetzRc4ZPX8XJ/DtAT56banbB6MnMXVzXNwT8gqumd56QDrHtuetxlg7e/IgsJNZDeKw6+w+QOkOEX7Cg7Go6xIkfFT2ZRQ79M55r+m0W58WhwjpPjD8xuLUz4bSfe9DpxcNPO8HoOB9iSUbtADHT+33inOW+9FGek6TmsAQ5YHuNxQd3PwbveJYEAaXPih4kHi5JeIfVd2SMReAd8WePvGdvrrXHCmAN9mDTtnlYDIcPpT7s8eUvxStG9VaSBW0zs96qWwidLriNtC3zEZAWAIcrGKEF4E/tdPnjM8LdttsjQxG8awdAnzFbsc0W1ShRUIJLwKdrQzVQuQ4edkOPzttTWpUtenNRWwY25SojiLvSsUj0YhxJ6cdpg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
